# Generated by Django 3.0.6 on 2020-05-24 15:53
# ALTER TABLE polls_useritem CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useritem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=254)),
                ('item_title', models.CharField(max_length=200)),
                ('item_contents', models.TextField()),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
